### ISSUE TITLE
Every page on the website on Firefox for Android is flickering

### ISSUE THREAD

**Issue by doronbehar** [okTurtles/groupincome.org-old#15]
What I mean by 'flickering' is that when I scroll the page, something up there in the menu above is changing it's height when I scroll up or down and the whole text is moving up and down instantly and rapidly so it's very hard to read anything.

It happens to me only on Android Firefox.

**Comment by taoeffect** [comment]
Is this happening anymore? We briefly had a [net neutrality](https://github.com/taoeffect/break-the-net) thing up but have since taken it down.

**Comment by doronbehar** [comment]
Well, Here is a video showing what I'm talking about:

[imgur](https://i.imgur.com/SaWAbg7.mp4)

**Comment by taoeffect** [comment]
Thanks for going to the trouble of making that video @doronbehar; I'm curious, does this also happen on https://fixingtao.com ?  I ask because those two sites use the same theme system, and I'm wondering if it's an issue with the theme itself or a customization we made.

**Comment by doronbehar** [comment]
No.
I think the difference that prevents https://fixingtao.com from getting this behaviour is the number of links at the top of every page. Yours has _blog_ , _videos_ ,  _FAQ_ , _Team_  etc..

**Comment by taoeffect** [comment]
OK, I think it might be the sticky header that's causing the issue. I'll update that soon (hopefully before the holidays are over) and will let you know here once I do so that you can verify it (as I don't have an Android phone to test this on). Thanks so much for reporting this, and happy holidays to you!

**Comment by doronbehar** [comment]
Happy [Festivus](https://www.youtube.com/watch?v=dS7-jcsB_WQ) for you too :) Cheers!

**Comment by taoeffect** [comment]
@doronbehar Before I start breaking features on the website, can you double-check if it's still having problems? I just updated the theme software, so maybe they fixed this issue.

**Comment by doronbehar** [comment]
Yes, it is still there.

**Comment by taoeffect** [comment]
@doronbehar Hmm.. OK, I thought maybe it was because of the top menu was set to be "sticky" when you scrolled, but it does that only on Desktop, not on Mobile, so it's probably not that. 

I also tried to reproduce the issue with both Firefox and Firefox Focus on iOS, and couldn't. And seeing as I don't have an Android phone ... yet ... it's difficult for me to debug this and figure out what's wrong.

I've added investigating this in more depth to my TODOs, but since this looks like it's going to be harder to figure out than I anticipated, it will take me a bit longer to get to it as there are higher priority items at the moment.

However, it is an important issue, so we will fix it once we get all the other TODO items out of the way. Right now our #1 focus is getting the prototype out the door. Once that's done we can devote resources to figuring out this mystery.

Thanks again for reporting the issue!

**Comment by doronbehar** [comment]
I tested it my self on Firefox on Linux in *Responsive Design mode* and it the issue didn't appear there either. It could be a bug with Firefox for Android now that I'm thinking about it.

**Comment by sandrina-p** [comment]
@doronbehar Can you tell us what's your Android version and Firefox version?

**Comment by doronbehar** [comment]
[Firefox Fennec 58.0.2](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_for_Android_build) from [F-droid](https://f-droid.org/packages/org.mozilla.fennec_fdroid/) on Android 7.1.2 (Lineage OS).

**Comment by taoeffect** [comment]
I should be clear (if it's not already mentioned somewhere), that the files in this github repo are _not_ what is used to create the existing site.

They are what we started out with when we were thinking of using a static-site generator, but then we migrated them over to a wordpress install so that we could take advantage of wordpress's commenting system

**Comment by pieer** [comment]
Fixed and live

**Comment by doronbehar** [comment]
That is correct.

**Comment by taoeffect** [comment]
Hey @doronbehar, we released updated our website. This issue may be fixed, so closing for now. Feel free to let us know if it's still a problem!
